management:
  endpoint:
    gateway:
      enabled: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins: ${CORS_ALLOWED_ORIGIN}
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      routes:
        - id: song_service
          uri: ${SONG_SERVICE_URL}
          predicates:
            - Path=/api/song/**
          filters:
            - StripPrefix=2
        - id: analytics_service
          uri: ${ANALYTICS_SERVICE_URL}
          predicates:
            - Path=/api/analytics/**
          filters:
            - StripPrefix=2
opentelemetry:
  exporter:
    otlp:
      protocol: http/protobuf
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSSSS} [%thread] %-5level %logger{36} [%X{traceId}] - %msg%n"
  level:
    root: INFO
    org.springframework.security: DEBUG
auth:
  public-endpoints:
    - path: /api/user/**
      method: POST
    - path: /api/song/allSongs
      method: GET
      
cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN}

server:
  address: 0.0.0.0