management:
  endpoint:
    gateway:
      enabled: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        allowed-origins: ${CORS_ALLOWED_ORIGIN}
        allowed-methods: "*"
        allow-headers: "*"
        allow-credentials: true
      routes:
        - id: song_service
          uri: ${SONG_SERVICE_URL}
          predicates:
            - Path=/api/song/**
        - id: analytics_service
          uri: ${ANALYTICS_SERVICE_URL}
          predicates:
            - Path=/api/analytics/**
auth:
  public-endpoints:
    - path: /api/user/**
      method: POST
cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN}
