spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: song_service
          uri: http://song-service
          predicates:
            - Path=/api/song/**
          filters:
            - StripPrefix=2
        - id: analytics_service
          uri: http://analytics-service
          predicates:
            - Path=/api/analytics/**
          filters:
            - StripPrefix=2
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
