apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          # image: judahlit/moodify_gateway:latest
          image: k3d-moodify:5000/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          env:
            - name: CORS_ALLOWED_ORIGIN
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: cors-allowed-origin
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/firebase-auth-creds.json
            - name: GOOGLE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: google-project-id
            - name: ANALYTICS_SERVICE_URL
              value: "http://analytics-service-service:8081"
            - name: SONG_SERVICE_URL
              value: "http://song-service-service:8082"
          volumeMounts:
            - name: firebase-auth-creds
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: firebase-auth-creds
          secret:
            secretName: firebase-auth-creds
