apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  rules:
  # - host: api.localhost
  #   http:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gateway-service
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway-deployment
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: judahlit/moodify_gateway:latest
          # image: k3d-moodify:5000/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
              cpu: "1"
            limits:
              memory: 2Gi
              cpu: "1"
          env:
            - name: CORS_ALLOWED_ORIGIN
              # value: "http://localhost:9080"
              value: "*"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/firebase-auth-creds.json
            - name: GOOGLE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: google-project-id
            - name: ANALYTICS_SERVICE_URL
              value: "http://analytics-service-service:8081"
            - name: SONG_SERVICE_URL
              value: "http://song-service-service:8082"
          volumeMounts:
            - name: firebase-auth-creds
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: firebase-auth-creds
          secret:
            secretName: firebase-auth-creds
